name:        chessIO
version:     0.9.0.0
github:      "mlang/chessIO"
license:     BSD3
author:      "Mario Lang"
maintainer:  "mlang@blind.guru"
copyright:   "2021 Mario Lang"

synopsis:    Basic chess library
category:    Game
description: A simple and fast library for generating legal chess moves.
  Also includes a module for communication with external processes that
  speak the UCI (Universal Chess Interface) protocol, a PGN parser/pretty printer,
  and Polyglot opening book support.
  On top of that, provides a console frontend program (cboard) that can be used
  to interactively play against UCI engines, and a terminal program (cbookview)
  to explore commonly played chess openings.

tested-with:
- GHC==8.6.5
- GHC==8.8.4
- GHC==8.10.5
- GHC==9.0.1

dependencies:
- attoparsec
- base >= 4.10 && < 5
- binary
- bytestring
- containers
- deepseq
- extra
- file-embed
- hashable
- lens
- megaparsec >= 9.0
- mono-traversable
- MonadRandom
- o-clock
- prettyprinter
- process
- random
- stm
- text
- template-haskell >= 2.9.0.0
- th-compat >= 0.1.2
- th-lift-instances
- unordered-containers
- vector
- vector-instances
- vector-binary-instances

extra-source-files:
- README.md
- ChangeLog.md
- book/eco.pgn
- book/twic-9g.bin

ghc-options:
- -O2

library:
  source-dirs: src
  exposed-modules:
  - Game.Chess
  - Game.Chess.ECO
  - Game.Chess.PGN
  - Game.Chess.Polyglot
  - Game.Chess.SAN
  - Game.Chess.Tree
  - Game.Chess.UCI

executables:
  cboard:
    main:         cboard.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    dependencies:
    - chessIO
    - haskeline
    - mtl
  polyplay:
    main:         polyplay.hs
    source-dirs:  app
    dependencies:
    - chessIO
    - optparse-applicative
    - time
  cbookview:
    main:         cbookview.hs
    source-dirs:  app
    ghc-options: -threaded
    dependencies:
    - chessIO
    - rosezipper
    - filepath
    - brick
    - lens
    - vty

tests:
  perft:
    main:                Perft.hs
    source-dirs:  test/perft
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -s"
    dependencies:
    - chessIO
    - directory
    - parallel
    - time
  polyglot:
    main:         Polyglot.hs
    source-dirs:  test/polyglot
    dependencies:
    - HUnit
    - chessIO
