name:        chessIO
version:     0.6.1.1
github:      "mlang/chessIO"
license:     BSD3
author:      "Mario Lang"
maintainer:  "mlang@blind.guru"
copyright:   "2021 Mario Lang"

synopsis:    Basic chess library
category:    Game
description: A simple and fast library for generating legal chess moves.
  Also includes a module for communication with external processes that
  speak the UCI (Universal Chess Interface) protocol, a PGN parser/pretty printer,
  and Polyglot opening book support.
  On top of that, provides a console frontend program (cboard) that can be used
  to interactively play against UCI engines, and a terminal program (cbookview)
  to explore commonly played chess openings.

dependencies:
- attoparsec
- base >= 4.10 && < 5
- binary
- bytestring
- containers
- extra
- file-embed
- hashable
- lens
- megaparsec >= 9.0
- mono-traversable
- MonadRandom
- o-clock
- prettyprinter
- process
- random
- stm
- text
- unordered-containers
- vector

default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- RecordWildCards
- OverloadedStrings
- PatternSynonyms
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

extra-source-files:
- README.md
- CHANGELOG.md
- book/scid.eco
- book/twic-9g.bin

ghc-options:
- -O2

library:
  source-dirs: src
  exposed-modules:
  - Game.Chess
  - Game.Chess.ECO
  - Game.Chess.PGN
  - Game.Chess.Polyglot
  - Game.Chess.SAN
  - Game.Chess.Tree
  - Game.Chess.UCI

executables:
  cboard:
    main:         cboard.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    dependencies:
    - chessIO
    - haskeline
    - mtl
  polyplay:
    main:         polyplay.hs
    source-dirs:  app
    dependencies:
    - chessIO
    - optparse-applicative
    - time
  cbookview:
    main:         cbookview.hs
    source-dirs:  app
    ghc-options: -threaded
    dependencies:
    - chessIO
    - rosezipper
    - filepath
    - brick
    - vty
    - microlens
    - microlens-th

tests:
  perft:
    main:                Perft.hs
    source-dirs:  test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -s"
    dependencies:
    - chessIO
    - directory
    - parallel
    - time
